from collections.abc import Iterable, Iterator
from importlib import import_module
from importlib.resources import path
from json import dumps, loads
from pathlib import Path
from re import fullmatch
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pytest import fixture, mark

from k8s_model_generator.generator import (
    generate,
    init_package,
    preprocess_input,
    preprocess_schema,
)


@fixture
def openapi_file() -> Iterator[Path]:
    with path("tests", "resources", "openapi.json") as p:
        yield p


def test_generate(openapi_file: Path, output_dir: Path) -> None:
    generate([openapi_file], output_dir)

    # custom_file_header
    with Path(output_dir, "test", "v1.py").open(encoding="utf-8") as stream:
        assert stream.readline() == "# generated by k8s-model-generator\n"
        assert stream.readline() == "\n"

    module = import_module(f"{output_dir.name}.test.v1")
    base = import_module(f"{output_dir.name}.base")

    # base_class
    assert issubclass(module.Pet, base.BaseModel)

    # enum_field_as_literal
    annotation = module.Pet.model_fields["kind"].annotation
    assert get_origin(annotation) is Literal
    assert get_args(annotation) == ("cat", "dog")

    # use_annotated, field_constraints
    annotation = module.Pet.__annotations__["name"]
    assert isinstance(annotation, str)
    assert fullmatch(r"Annotated\[.+?\]", annotation)

    # snake_case_field
    assert "says_what" in module.Pet.model_fields

    # strict_nullable
    annotation = module.Pet.model_fields["says_what"].annotation
    assert annotation is str

    # use_field_description
    description = module.Pet.model_fields["says_what"].description
    assert description is None

    # use_type_alias
    pet = module.Pet.model_validate({"kind": "cat", "age": 1})
    assert isinstance(pet.age, int)


def test_generate_no_snake_case(openapi_file: Path, output_dir: Path) -> None:
    generate([openapi_file], output_dir, snake_case_fields=False)
    module = import_module(f"{output_dir.name}.test.v1")
    pet = module.Pet.model_validate({"kind": "cat"})
    assert hasattr(pet, "saysWhat")


@fixture
def subpackage_output_dir(output_dir: Path) -> Path:
    output_dir.mkdir()
    Path(output_dir, "__init__.py")
    return Path(output_dir, "models")


def test_generate_subpackage(openapi_file: Path, output_dir: Path) -> None:
    output_dir.mkdir()
    Path(output_dir, "__init__.py")

    generate(
        [openapi_file],
        Path(output_dir, "models"),
        package_name=f"{output_dir.name}.models",
    )

    module = import_module(f"{output_dir.name}.models.test.v1")
    base = import_module(f"{output_dir.name}.models.base")
    assert issubclass(module.Pet, base.BaseModel)


def test_generate_from_kubernetes_openapi(
    kubernetes_openapi_v3_spec_files: Iterable[Path], output_dir: Path
) -> None:
    generate(kubernetes_openapi_v3_spec_files, output_dir)
    base = import_module(f"{output_dir.name}.base")
    core_v1 = import_module(f"{output_dir.name}.io.k8s.api.core.v1")
    assert issubclass(core_v1.Pod, base.BaseModel)
    networking_v1 = import_module(f"{output_dir.name}.io.k8s.api.networking.v1")
    assert issubclass(networking_v1.NetworkPolicy, base.BaseModel)


@mark.parametrize(
    argnames=("title", "schema", "preprocessed"),
    argvalues=[
        (
            "io.k8s.apimachinery.pkg.util.intstr.IntOrString",
            {
                "format": "int-or-string",
                "oneOf": [
                    {"type": "integer"},
                    {"type": "string"},
                ],
            },
            {
                "oneOf": [
                    {"type": "integer"},
                    {"type": "string"},
                ],
            },
        )
    ],
)
def test_preprocess_schema(
    title: str, schema: dict[str, Any], preprocessed: dict[str, Any]
) -> None:
    preprocess_schema(title, schema)
    assert schema == preprocessed


@fixture
def input_dir(tmp_path: Path) -> Path:
    _input_dir = Path(tmp_path, "input")
    _input_dir.mkdir()
    return _input_dir


@fixture
def preprocessed_file(tmp_path: Path) -> Path:
    return Path(tmp_path, "preprocessed_openapi.json")


@mark.parametrize(
    argnames=("input_openapis", "preprocessed_openapi"),
    argvalues=[
        (
            [
                {
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Kubernetes",
                        "version": "unversioned",
                    },
                    "paths": {},
                    "components": {
                        "schemas": {
                            "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
                                "format": "int-or-string",
                                "oneOf": [
                                    {"type": "integer"},
                                    {"type": "string"},
                                ],
                            }
                        },
                    },
                },
            ],
            {
                "openapi": "3.0.0",
                "info": {
                    "title": "k8s-model-generator",
                    "version": "unversioned",
                },
                "paths": {},
                "components": {
                    "schemas": {
                        "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
                            "oneOf": [
                                {"type": "integer"},
                                {"type": "string"},
                            ],
                        }
                    },
                },
            },
        ),
        (
            [
                {
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Kubernetes",
                        "version": "unversioned",
                    },
                    "paths": {},
                    "components": {
                        "schemas": {
                            "test.Foo": {
                                "type": "object",
                                "properties": {
                                    "foo1": {
                                        "type": "string",
                                    }
                                },
                            }
                        },
                    },
                },
                {
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Kubernetes",
                        "version": "unversioned",
                    },
                    "paths": {},
                    "components": {
                        "schemas": {
                            "test.Foo": {
                                "type": "object",
                                "properties": {
                                    "foo2": {
                                        "type": "string",
                                    }
                                },
                            },
                            "test.Bar": {
                                "type": "object",
                                "properties": {
                                    "bar": {
                                        "type": "string",
                                    }
                                },
                            },
                        },
                    },
                },
            ],
            {
                "openapi": "3.0.0",
                "info": {
                    "title": "k8s-model-generator",
                    "version": "unversioned",
                },
                "paths": {},
                "components": {
                    "schemas": {
                        "test.Foo": {
                            "type": "object",
                            "properties": {
                                "foo1": {
                                    "type": "string",
                                }
                            },
                        },
                        "test.Bar": {
                            "type": "object",
                            "properties": {
                                "bar": {
                                    "type": "string",
                                }
                            },
                        },
                    },
                },
            },
        ),
    ],
)
def test_preprocess_input(
    input_openapis: list[dict[str, Any]],
    input_dir: Path,
    preprocessed_file: Path,
    preprocessed_openapi: dict[str, Any],
) -> None:
    input_files: list[Path] = []
    for i, input_openapi in enumerate(input_openapis):
        input_file = Path(input_dir, f"{i}_openapi.json")
        input_file.write_text(dumps(input_openapi))
        input_files.append(input_file)
    preprocess_input(input_files, preprocessed_file)
    assert loads(preprocessed_file.read_text()) == preprocessed_openapi


@mark.parametrize(
    argnames=("create_output_dir",),
    argvalues=[
        (False,),
        (True,),
    ],
)
def test_init_package(output_dir: Path, create_output_dir: bool) -> None:
    if create_output_dir:
        output_dir.mkdir()
    init_package(output_dir)
    module = import_module(f"{output_dir.name}.base")
    assert issubclass(module.BaseModel, BaseModel)
