from collections.abc import Iterable, Iterator
from importlib import import_module
from importlib.resources import path
from json import dumps, loads
from pathlib import Path
from re import fullmatch
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pytest import fixture, mark

from k8s_model_generator.generator import generate, preprocess_input, preprocess_schema

from .utils import Package


@fixture
def openapi_file() -> Iterator[Path]:
    with path("tests", "resources", "openapi.json") as p:
        yield p


def test_custom_file_header(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    with Path(unique_package.dir, "test", "v1.py").open(encoding="utf-8") as stream:
        assert stream.readline() == "# generated by k8s-model-generator\n"
        assert stream.readline() == "\n"


def test_enum_field_as_literal(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    module = import_module(f"{unique_package.name}.test.v1")
    annotation = module.Pet.model_fields["kind"].annotation
    assert get_origin(annotation) is Literal
    assert get_args(annotation) == ("cat", "dog")


def test_use_annotated(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    module = import_module(f"{unique_package.name}.test.v1")
    name_annotation = module.Pet.__annotations__["name"]
    assert isinstance(name_annotation, str)
    assert fullmatch(r"Annotated\[.+?\]", name_annotation)


def test_snake_case_field(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    module = import_module(f"{unique_package.name}.test.v1")
    pet = module.Pet.model_validate({"kind": "cat"})
    assert hasattr(pet, "says_what")


def test_no_snake_case_field(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir, snake_case_fields=False)
    module = import_module(f"{unique_package.name}.test.v1")
    pet = module.Pet.model_validate({"kind": "cat"})
    assert hasattr(pet, "saysWhat")


def test_strict_nullable(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    module = import_module(f"{unique_package.name}.test.v1")
    annotation = module.Pet.model_fields["says_what"].annotation
    assert annotation is str


def test_use_field_description(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    module = import_module(f"{unique_package.name}.test.v1")
    description = module.Pet.model_fields["says_what"].description
    assert description is None


def test_use_type_alias(openapi_file: Path, unique_package: Package) -> None:
    generate([openapi_file], unique_package.dir)
    module = import_module(f"{unique_package.name}.test.v1")
    pet = module.Pet.model_validate({"kind": "cat", "age": 1})
    assert isinstance(pet.age, int)


def test_generate_from_kubernetes_openapi(
    kubernetes_openapi_v3_spec_files: Iterable[Path], unique_package: Package
) -> None:
    generate(kubernetes_openapi_v3_spec_files, unique_package.dir)
    core_v1 = import_module(f"{unique_package.name}.io.k8s.api.core.v1")
    assert issubclass(core_v1.Pod, BaseModel)
    networking_v1 = import_module(f"{unique_package.name}.io.k8s.api.networking.v1")
    assert issubclass(networking_v1.NetworkPolicy, BaseModel)


@mark.parametrize(
    argnames=("title", "schema", "preprocessed"),
    argvalues=[
        (
            "io.k8s.apimachinery.pkg.util.intstr.IntOrString",
            {
                "format": "int-or-string",
                "oneOf": [
                    {"type": "integer"},
                    {"type": "string"},
                ],
            },
            {
                "oneOf": [
                    {"type": "integer"},
                    {"type": "string"},
                ],
            },
        )
    ],
)
def test_preprocess_schema(
    title: str, schema: dict[str, Any], preprocessed: dict[str, Any]
) -> None:
    preprocess_schema(title, schema)
    assert schema == preprocessed


@fixture
def input_dir(tmp_path: Path) -> Path:
    _input_dir = Path(tmp_path, "input")
    _input_dir.mkdir()
    return _input_dir


@fixture
def preprocessed_file(tmp_path: Path) -> Path:
    return Path(tmp_path, "preprocessed_openapi.json")


@mark.parametrize(
    argnames=("input_openapis", "preprocessed_openapi"),
    argvalues=[
        (
            [
                {
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Kubernetes",
                        "version": "unversioned",
                    },
                    "paths": {},
                    "components": {
                        "schemas": {
                            "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
                                "format": "int-or-string",
                                "oneOf": [
                                    {"type": "integer"},
                                    {"type": "string"},
                                ],
                            }
                        },
                    },
                },
            ],
            {
                "openapi": "3.0.0",
                "info": {
                    "title": "k8s-model-generator",
                    "version": "unversioned",
                },
                "paths": {},
                "components": {
                    "schemas": {
                        "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
                            "oneOf": [
                                {"type": "integer"},
                                {"type": "string"},
                            ],
                        }
                    },
                },
            },
        ),
        (
            [
                {
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Kubernetes",
                        "version": "unversioned",
                    },
                    "paths": {},
                    "components": {
                        "schemas": {
                            "test.Foo": {
                                "type": "object",
                                "properties": {
                                    "foo1": {
                                        "type": "string",
                                    }
                                },
                            }
                        },
                    },
                },
                {
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Kubernetes",
                        "version": "unversioned",
                    },
                    "paths": {},
                    "components": {
                        "schemas": {
                            "test.Foo": {
                                "type": "object",
                                "properties": {
                                    "foo2": {
                                        "type": "string",
                                    }
                                },
                            },
                            "test.Bar": {
                                "type": "object",
                                "properties": {
                                    "bar": {
                                        "type": "string",
                                    }
                                },
                            },
                        },
                    },
                },
            ],
            {
                "openapi": "3.0.0",
                "info": {
                    "title": "k8s-model-generator",
                    "version": "unversioned",
                },
                "paths": {},
                "components": {
                    "schemas": {
                        "test.Foo": {
                            "type": "object",
                            "properties": {
                                "foo1": {
                                    "type": "string",
                                }
                            },
                        },
                        "test.Bar": {
                            "type": "object",
                            "properties": {
                                "bar": {
                                    "type": "string",
                                }
                            },
                        },
                    },
                },
            },
        ),
    ],
)
def test_preprocess_input(
    input_openapis: list[dict[str, Any]],
    input_dir: Path,
    preprocessed_file: Path,
    preprocessed_openapi: dict[str, Any],
) -> None:
    input_files: list[Path] = []
    for i, input_openapi in enumerate(input_openapis):
        input_file = Path(input_dir, f"{i}_openapi.json")
        input_file.write_text(dumps(input_openapi))
        input_files.append(input_file)
    preprocess_input(input_files, preprocessed_file)
    assert loads(preprocessed_file.read_text()) == preprocessed_openapi
