from collections.abc import Iterable
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from datamodel_code_generator import (
    LiteralType,
    PythonVersion,
    PythonVersionMin,
    TargetPydanticVersion,
)
from datamodel_code_generator import (
    generate as _generate,
)
from datamodel_code_generator.config import GenerateConfig
from datamodel_code_generator.enums import DataModelType, InputFileType

from k8s_model_generator.openapi.v3 import OpenAPIObject


def fix_int_or_string_warnings(schema: dict[str, Any]) -> None:
    """Fix warnings about unknown 'int-or-string' format.

    Fix 'datamodel-code-generator' warnings about unknown 'int-or-string' format:

    * UserWarning: format of 'int-or-string' not understood for 'integer' - using
      default
    * UserWarning: format of 'int-or-string' not understood for 'string' - using
      default
    """
    if "format" in schema and schema["format"] == "int-or-string":
        schema.pop("format")


def preprocess_schema(title: str, schema: dict[str, Any]) -> None:
    if title == "io.k8s.apimachinery.pkg.util.intstr.IntOrString":
        fix_int_or_string_warnings(schema)


def preprocess_input(input_files: Iterable[Path], preprocessed_file: Path) -> None:
    schemas: dict[str, dict[str, Any]] = {}
    for input_file in input_files:
        openapi = OpenAPIObject.model_validate_json(
            input_file.read_text(encoding="utf-8")
        )
        for title, schema in map(
            lambda item: (item[0], item[1].model_dump(mode="json")),
            openapi.components.schemas.items(),
        ):
            if title not in schemas:
                preprocess_schema(title, schema)
                schemas[title] = schema
    preprocessed_openapi = OpenAPIObject.model_validate(
        {
            "openapi": "3.0.0",
            "info": {
                "title": "k8s-model-generator",
                "version": "unversioned",
            },
            "paths": {},
            "components": {
                "schemas": schemas,
            },
        }
    )
    preprocessed_file.write_text(
        data=preprocessed_openapi.model_dump_json(ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def generate(
    input_files: Iterable[Path],
    output_dir: Path,
    snake_case_fields: bool = True,
    python_version: str = "minimal",
    pydantic_version: str = "2.11",
) -> None:
    with TemporaryDirectory() as tmp_dir:
        preprocessed_file = Path(tmp_dir, "openapi.json")
        preprocess_input(input_files, preprocessed_file)
        _generate(
            input_=preprocessed_file,
            config=GenerateConfig(
                input_file_type=InputFileType.OpenAPI,
                output=output_dir,
                output_model_type=DataModelType.PydanticV2BaseModel,
                target_pydantic_version=TargetPydanticVersion(pydantic_version),
                target_python_version=(
                    PythonVersionMin
                    if python_version == "minimal"
                    else PythonVersion(python_version)
                ),
                custom_file_header="# generated by k8s-model-generator",
                snake_case_field=snake_case_fields,
                use_annotated=True,
                field_constraints=True,
                enum_field_as_literal=LiteralType.All,
                strict_nullable=True,
                use_field_description=True,
                use_type_alias=True,
                formatters=[],
            ),
        )
